bdk:
  host: develop2.symphony.com
  bot:
    username: trade-buddy
    privateKey.path: rsa/privatekey.pem

logging.level:
  org:
    springframework: error
    apache: error
  com:
    symphony: info
    symphony.bdk:
      workflow:
        swadl: error
        engine.executor.DebugExecutor: debug
    zaxxer: error
