name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.outputs.tags }}
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 17

    - uses: gradle/gradle-build-action@v2
      with:
        arguments: botJar

    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: ghcr.io/${{ github.repository }}
        flavor: latest=false
        tags: type=sha

    - uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}

  release-to-preview:
    needs: build
    runs-on: ubuntu-latest
    environment: 'Preview'
    steps:
    - uses: actions/checkout@v3

    - uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.UAT_GKE_AUTH }}

    - uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ secrets.UAT_GKE_CLUSTER }}
        location: ${{ secrets.UAT_GKE_ZONE }}

    - env:
        DEPLOYMENT: ${{ secrets.DEPLOYMENT }}
      run: |
        kubectl set image deployment/${DEPLOYMENT} ${DEPLOYMENT}=${{ needs.build.outputs.tag }}
        kubectl rollout status deployment/${DEPLOYMENT}
